//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NerfTeleoperation
{
    [Serializable]
    public class SplatRequestRequest : Message
    {
        public const string k_RosMessageName = "nerf_teleoperation_msgs/SplatRequest";
        public override string RosMessageName => k_RosMessageName;

        //  Input of sh degree
        public byte sh_degree;

        public SplatRequestRequest()
        {
            this.sh_degree = 0;
        }

        public SplatRequestRequest(byte sh_degree)
        {
            this.sh_degree = sh_degree;
        }

        public static SplatRequestRequest Deserialize(MessageDeserializer deserializer) => new SplatRequestRequest(deserializer);

        private SplatRequestRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sh_degree);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sh_degree);
        }

        public override string ToString()
        {
            return "SplatRequestRequest: " +
            "\nsh_degree: " + sh_degree.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
