//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.PsyonicSdkRos
{
    [Serializable]
    public class TouchStateMsg : Message
    {
        public const string k_RosMessageName = "psyonic_sdk_ros/TouchState";
        public override string RosMessageName => k_RosMessageName;

        //  This is a message that holds data to describe the data from touch sensors.
        // 
        //  The touch sensor data is defined by:
        //   * the force on the sensor (in Newtons).
        // 
        //  Each sensor is uniquely identified by its name
        //  The header specifies the time at which the data was recorded. All the touch data
        //  in one message have to be recorded at the same time.
        // 
        //  All arrays in this message should have the same size, or be empty.
        //  This is the only way to uniquely associate the sensor name with the correct
        //  data.
        public HeaderMsg header;
        public string[] name;
        public double[] force;
        public double[] raw;

        public TouchStateMsg()
        {
            this.header = new HeaderMsg();
            this.name = new string[0];
            this.force = new double[0];
            this.raw = new double[0];
        }

        public TouchStateMsg(HeaderMsg header, string[] name, double[] force, double[] raw)
        {
            this.header = header;
            this.name = name;
            this.force = force;
            this.raw = raw;
        }

        public static TouchStateMsg Deserialize(MessageDeserializer deserializer) => new TouchStateMsg(deserializer);

        private TouchStateMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.name, deserializer.ReadLength());
            deserializer.Read(out this.force, sizeof(double), deserializer.ReadLength());
            deserializer.Read(out this.raw, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.name);
            serializer.Write(this.name);
            serializer.WriteLength(this.force);
            serializer.Write(this.force);
            serializer.WriteLength(this.raw);
            serializer.Write(this.raw);
        }

        public override string ToString()
        {
            return "TouchStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nname: " + System.String.Join(", ", name.ToList()) +
            "\nforce: " + System.String.Join(", ", force.ToList()) +
            "\nraw: " + System.String.Join(", ", raw.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
