//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Haptic
{
    [Serializable]
    public class HapticReadingsMsg : Message
    {
        public const string k_RosMessageName = "haptic_msgs/HapticReadings";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        public TaxelMsg index_tip;
        public TaxelMsg middle_tip;
        public TaxelMsg ring_tip;
        public TaxelMsg pinky_tip;
        public TaxelMsg thumb_tip;
        public TaxelMsg palm;
        public bool is_right_hand;

        public HapticReadingsMsg()
        {
            this.header = new HeaderMsg();
            this.index_tip = new TaxelMsg();
            this.middle_tip = new TaxelMsg();
            this.ring_tip = new TaxelMsg();
            this.pinky_tip = new TaxelMsg();
            this.thumb_tip = new TaxelMsg();
            this.palm = new TaxelMsg();
            this.is_right_hand = false;
        }

        public HapticReadingsMsg(HeaderMsg header, TaxelMsg index_tip, TaxelMsg middle_tip, TaxelMsg ring_tip, TaxelMsg pinky_tip, TaxelMsg thumb_tip, TaxelMsg palm, bool is_right_hand)
        {
            this.header = header;
            this.index_tip = index_tip;
            this.middle_tip = middle_tip;
            this.ring_tip = ring_tip;
            this.pinky_tip = pinky_tip;
            this.thumb_tip = thumb_tip;
            this.palm = palm;
            this.is_right_hand = is_right_hand;
        }

        public static HapticReadingsMsg Deserialize(MessageDeserializer deserializer) => new HapticReadingsMsg(deserializer);

        private HapticReadingsMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.index_tip = TaxelMsg.Deserialize(deserializer);
            this.middle_tip = TaxelMsg.Deserialize(deserializer);
            this.ring_tip = TaxelMsg.Deserialize(deserializer);
            this.pinky_tip = TaxelMsg.Deserialize(deserializer);
            this.thumb_tip = TaxelMsg.Deserialize(deserializer);
            this.palm = TaxelMsg.Deserialize(deserializer);
            deserializer.Read(out this.is_right_hand);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.index_tip);
            serializer.Write(this.middle_tip);
            serializer.Write(this.ring_tip);
            serializer.Write(this.pinky_tip);
            serializer.Write(this.thumb_tip);
            serializer.Write(this.palm);
            serializer.Write(this.is_right_hand);
        }

        public override string ToString()
        {
            return "HapticReadingsMsg: " +
            "\nheader: " + header.ToString() +
            "\nindex_tip: " + index_tip.ToString() +
            "\nmiddle_tip: " + middle_tip.ToString() +
            "\nring_tip: " + ring_tip.ToString() +
            "\npinky_tip: " + pinky_tip.ToString() +
            "\nthumb_tip: " + thumb_tip.ToString() +
            "\npalm: " + palm.ToString() +
            "\nis_right_hand: " + is_right_hand.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
