//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Voxblox
{
    [Serializable]
    public class MeshMsg : Message
    {
        public const string k_RosMessageName = "voxblox_msgs/Mesh";
        public override string RosMessageName => k_RosMessageName;

        //  vertex positions rounded to nearest BLOCK_EDGE_LENGTH/65535 
        //  no alpha information
        public Std.HeaderMsg header;
        public float block_edge_length;
        public MeshBlockMsg[] mesh_blocks;

        public MeshMsg()
        {
            this.header = new Std.HeaderMsg();
            this.block_edge_length = 0.0f;
            this.mesh_blocks = new MeshBlockMsg[0];
        }

        public MeshMsg(Std.HeaderMsg header, float block_edge_length, MeshBlockMsg[] mesh_blocks)
        {
            this.header = header;
            this.block_edge_length = block_edge_length;
            this.mesh_blocks = mesh_blocks;
        }

        public static MeshMsg Deserialize(MessageDeserializer deserializer) => new MeshMsg(deserializer);

        private MeshMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.block_edge_length);
            deserializer.Read(out this.mesh_blocks, MeshBlockMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.block_edge_length);
            serializer.WriteLength(this.mesh_blocks);
            serializer.Write(this.mesh_blocks);
        }

        public override string ToString()
        {
            return "MeshMsg: " +
            "\nheader: " + header.ToString() +
            "\nblock_edge_length: " + block_edge_length.ToString() +
            "\nmesh_blocks: " + System.String.Join(", ", mesh_blocks.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
