//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Voxblox
{
    [Serializable]
    public class MeshBlockMsg : Message
    {
        public const string k_RosMessageName = "voxblox_msgs/MeshBlock";
        public override string RosMessageName => k_RosMessageName;

        //  vertex positions rounded to nearest BLOCK_EDGE_LENGTH/65535 
        //  no alpha information
        //  Index of meshed points in block map
        public long[] index;
        //  Triangle information (always in groups of 3)
        public ushort[] x;
        public ushort[] y;
        public ushort[] z;
        //  Color information may be missing
        public byte[] r;
        public byte[] g;
        public byte[] b;

        public MeshBlockMsg()
        {
            this.index = new long[3];
            this.x = new ushort[0];
            this.y = new ushort[0];
            this.z = new ushort[0];
            this.r = new byte[0];
            this.g = new byte[0];
            this.b = new byte[0];
        }

        public MeshBlockMsg(long[] index, ushort[] x, ushort[] y, ushort[] z, byte[] r, byte[] g, byte[] b)
        {
            this.index = index;
            this.x = x;
            this.y = y;
            this.z = z;
            this.r = r;
            this.g = g;
            this.b = b;
        }

        public static MeshBlockMsg Deserialize(MessageDeserializer deserializer) => new MeshBlockMsg(deserializer);

        private MeshBlockMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.index, sizeof(long), 3);
            deserializer.Read(out this.x, sizeof(ushort), deserializer.ReadLength());
            deserializer.Read(out this.y, sizeof(ushort), deserializer.ReadLength());
            deserializer.Read(out this.z, sizeof(ushort), deserializer.ReadLength());
            deserializer.Read(out this.r, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.g, sizeof(byte), deserializer.ReadLength());
            deserializer.Read(out this.b, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.index);
            serializer.WriteLength(this.x);
            serializer.Write(this.x);
            serializer.WriteLength(this.y);
            serializer.Write(this.y);
            serializer.WriteLength(this.z);
            serializer.Write(this.z);
            serializer.WriteLength(this.r);
            serializer.Write(this.r);
            serializer.WriteLength(this.g);
            serializer.Write(this.g);
            serializer.WriteLength(this.b);
            serializer.Write(this.b);
        }

        public override string ToString()
        {
            return "MeshBlockMsg: " +
            "\nindex: " + System.String.Join(", ", index.ToList()) +
            "\nx: " + System.String.Join(", ", x.ToList()) +
            "\ny: " + System.String.Join(", ", y.ToList()) +
            "\nz: " + System.String.Join(", ", z.ToList()) +
            "\nr: " + System.String.Join(", ", r.ToList()) +
            "\ng: " + System.String.Join(", ", g.ToList()) +
            "\nb: " + System.String.Join(", ", b.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
